# Generated by Django 3.0.8 on 2020-08-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='질병 이름')),
                ('desc', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '질병',
                'verbose_name_plural': '질병',
            },
        ),
    ]
