# Generated by Django 3.0.8 on 2020-08-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20200810_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientdata',
            name='disease',
            field=models.ManyToManyField(blank=True, null=True, to='datas.Disease', verbose_name='관련 질병'),
        ),
    ]
