# Generated by Django 3.0.8 on 2020-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_auto_20200810_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='연령')),
                ('desc', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '연령 데이터',
                'verbose_name_plural': '연령 데이터',
            },
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='견종')),
            ],
            options={
                'verbose_name': '품종 데이터',
                'verbose_name_plural': '품종 데이터',
            },
        ),
    ]
