# Generated by Django 3.0.8 on 2020-08-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_agerange_dogbreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerange',
            name='disease',
            field=models.ManyToManyField(blank=True, null=True, to='datas.Disease', verbose_name='관련 질병'),
        ),
        migrations.AddField(
            model_name='agerange',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 개월수'),
        ),
        migrations.AddField(
            model_name='agerange',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='최소 개월수'),
        ),
    ]
