# Generated by Django 3.0.8 on 2020-08-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_auto_20200811_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerange',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='슬러그'),
        ),
    ]
