# Generated by Django 3.0.8 on 2020-08-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_agerange_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerange',
            name='caution_disease',
            field=models.TextField(blank=True, null=True, verbose_name='주의 질병(피부/관절/눈/심장/신장/방광/치아/간/췌장염/종양/비타민결핍/칼슘결핍/면역력결핍)'),
        ),
    ]
