# Generated by Django 3.0.8 on 2020-08-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0010_auto_20200811_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agerange',
            name='a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='피부(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='심장(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='e',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='신장(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='f',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='방광(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='치아(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='h',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='간(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='i',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='췌장염(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='j',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='종양(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='k',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='비타민결핍(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='l',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='면역력결핍(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='칼슘결핍(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='n',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='장건강(위험도 %)'),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='o',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='비만(위험도 %)'),
        ),
    ]
