# Generated by Django 3.0.8 on 2020-07-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='사료 이름')),
                ('types', models.CharField(choices=[('촉촉', '촉촉'), ('처방', '처방')], max_length=2, verbose_name='분류')),
                ('calorie', models.CharField(max_length=1000, verbose_name='칼로리')),
                ('moisture', models.CharField(max_length=1000, verbose_name='수분량')),
                ('crude_protein', models.CharField(max_length=1000, verbose_name='조단백')),
                ('crude_fat', models.CharField(max_length=1000, verbose_name='조지방')),
                ('crude_fiber', models.CharField(max_length=1000, verbose_name='조섬유')),
                ('crude_ash', models.CharField(max_length=1000, verbose_name='조회분')),
                ('calcium', models.CharField(max_length=1000, verbose_name='칼슘')),
                ('phosphorus', models.CharField(max_length=1000, verbose_name='인')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='영양제 이름')),
                ('calorie', models.CharField(max_length=1000, verbose_name='칼로리')),
                ('moisture', models.CharField(max_length=1000, verbose_name='수분량')),
                ('crude_protein', models.CharField(max_length=1000, verbose_name='조단백')),
                ('crude_fat', models.CharField(max_length=1000, verbose_name='조지방')),
                ('crude_fiber', models.CharField(max_length=1000, verbose_name='조섬유')),
                ('crude_ash', models.CharField(max_length=1000, verbose_name='조회분')),
                ('calcium', models.CharField(max_length=1000, verbose_name='칼슘')),
                ('phosphorus', models.CharField(max_length=1000, verbose_name='인')),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='간식 이름')),
            ],
        ),
    ]
