# Generated by Django 2.2.7 on 2020-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0002_auto_20200713_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangedFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='사료 이름')),
                ('types', models.CharField(choices=[('촉촉', '촉촉'), ('처방', '처방')], max_length=2, verbose_name='분류')),
                ('calorie', models.CharField(max_length=1000, verbose_name='칼로리(kcal/1g)')),
                ('moisture', models.CharField(max_length=1000, verbose_name='수분량(ml/1g)')),
                ('crude_protein', models.CharField(max_length=1000, verbose_name='조단백(g/1g)')),
                ('crude_fat', models.CharField(max_length=1000, verbose_name='조지방(g/1g)')),
                ('crude_fiber', models.CharField(max_length=1000, verbose_name='조섬유(g/1g)')),
                ('crude_ash', models.CharField(max_length=1000, verbose_name='조회분(g/1g)')),
                ('calcium', models.CharField(max_length=1000, verbose_name='칼슘(g/1g)')),
                ('phosphorus', models.CharField(max_length=1000, verbose_name='인(g/1g)')),
            ],
            options={
                'verbose_name': '사료 환산',
                'verbose_name_plural': '사료 환산',
            },
        ),
        migrations.AlterField(
            model_name='feed',
            name='calcium',
            field=models.CharField(max_length=1000, verbose_name='칼슘(%)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='calorie',
            field=models.CharField(max_length=1000, verbose_name='칼로리(kcal/kg)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='crude_ash',
            field=models.CharField(max_length=1000, verbose_name='조회분(%)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='crude_fat',
            field=models.CharField(max_length=1000, verbose_name='조지방(%)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='crude_fiber',
            field=models.CharField(max_length=1000, verbose_name='조섬유(%)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='crude_protein',
            field=models.CharField(max_length=1000, verbose_name='조단백(%)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='moisture',
            field=models.CharField(max_length=1000, verbose_name='수분량(%)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='phosphorus',
            field=models.CharField(max_length=1000, verbose_name='인(%)'),
        ),
    ]
