# Generated by Django 3.0.8 on 2020-07-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0005_auto_20200714_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='standard',
        ),
        migrations.AlterField(
            model_name='feed',
            name='calorie',
            field=models.CharField(max_length=1000, verbose_name='칼로리(kcal/100g)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='calcium',
            field=models.CharField(max_length=1000, verbose_name='칼슘(%)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='calorie',
            field=models.CharField(max_length=1000, verbose_name='칼로리(kcal/100g)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='crude_ash',
            field=models.CharField(max_length=1000, verbose_name='조회분(%)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='crude_fat',
            field=models.CharField(max_length=1000, verbose_name='조지방(%)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='crude_fiber',
            field=models.CharField(max_length=1000, verbose_name='조섬유(%)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='crude_protein',
            field=models.CharField(max_length=1000, verbose_name='조단백(%)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='moisture',
            field=models.CharField(max_length=1000, verbose_name='수분량(%)'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='phosphorus',
            field=models.CharField(max_length=1000, verbose_name='인(%)'),
        ),
    ]
