# Generated by Django 3.0.8 on 2020-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0006_auto_20200714_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangedNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='영양제 이름')),
                ('calorie', models.CharField(max_length=1000, verbose_name='칼로리(kcal)')),
                ('moisture', models.CharField(max_length=1000, verbose_name='수분량(g)')),
                ('crude_protein', models.CharField(max_length=1000, verbose_name='조단백(g)')),
                ('crude_fat', models.CharField(max_length=1000, verbose_name='조지방(g)')),
                ('crude_fiber', models.CharField(max_length=1000, verbose_name='조섬유(g)')),
                ('crude_ash', models.CharField(max_length=1000, verbose_name='조회분(g)')),
                ('calcium', models.CharField(max_length=1000, verbose_name='칼슘(g)')),
                ('phosphorus', models.CharField(max_length=1000, verbose_name='인(g)')),
            ],
            options={
                'verbose_name': '영양제 환산 - [1g당 성분양]',
                'verbose_name_plural': '영양제 환산- [1g당 성분양]',
            },
        ),
        migrations.AlterModelOptions(
            name='exchangedfeed',
            options={'verbose_name': '사료 환산 - [1g당 성분양]', 'verbose_name_plural': '사료 환산- [1g당 성분양]'},
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='calcium',
            field=models.CharField(max_length=1000, verbose_name='칼슘(g)'),
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='calorie',
            field=models.CharField(max_length=1000, verbose_name='칼로리(kcal)'),
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='crude_ash',
            field=models.CharField(max_length=1000, verbose_name='조회분(g)'),
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='crude_fat',
            field=models.CharField(max_length=1000, verbose_name='조지방(g)'),
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='crude_fiber',
            field=models.CharField(max_length=1000, verbose_name='조섬유(g)'),
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='crude_protein',
            field=models.CharField(max_length=1000, verbose_name='조단백(g)'),
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='moisture',
            field=models.CharField(max_length=1000, verbose_name='수분량(g)'),
        ),
        migrations.AlterField(
            model_name='exchangedfeed',
            name='phosphorus',
            field=models.CharField(max_length=1000, verbose_name='인(g)'),
        ),
    ]
