# Generated by Django 2.2.7 on 2020-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0008_auto_20200805_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='간식 이름')),
                ('calorie', models.CharField(max_length=1000, verbose_name='칼로리(kcal/100g)')),
                ('moisture', models.CharField(max_length=1000, verbose_name='수분량(%)')),
                ('crude_protein', models.CharField(max_length=1000, verbose_name='조단백(%)')),
                ('crude_fat', models.CharField(max_length=1000, verbose_name='조지방(%)')),
                ('crude_fiber', models.CharField(max_length=1000, verbose_name='조섬유(%)')),
                ('crude_ash', models.CharField(max_length=1000, verbose_name='조회분(%)')),
                ('calcium', models.CharField(max_length=1000, verbose_name='칼슘(%)')),
                ('phosphorus', models.CharField(max_length=1000, verbose_name='인(%)')),
            ],
            options={
                'verbose_name': '간식',
                'verbose_name_plural': '간식',
            },
        ),
    ]
