# Generated by Django 3.0.8 on 2020-08-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0010_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='title',
            new_name='name',
        ),
    ]
