# Generated by Django 3.0.8 on 2020-08-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0011_auto_20200810_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
