# Generated by Django 3.0.8 on 2020-08-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datas', '0011_auto_20200811_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20, verbose_name='주인 계정')),
                ('name', models.CharField(max_length=20, verbose_name='반려동물 이름')),
                ('age', models.CharField(max_length=50, verbose_name='반려동물 생년월일')),
                ('weight', models.CharField(max_length=50, verbose_name='체중')),
                ('image', models.ImageField(default='mypet_images/default/dog.jpg', upload_to='mypet_images', verbose_name='반려동물 이미지')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datas.DogBreed')),
            ],
            options={
                'verbose_name': '등록된 반려 동물',
                'verbose_name_plural': '등록된 반려 동물',
            },
        ),
    ]
