# Generated by Django 3.0.8 on 2020-08-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypet',
            name='image',
        ),
    ]
