# Generated by Django 3.0.8 on 2020-08-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_mypet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypet',
            name='image',
            field=models.ImageField(default='mypet_images/default/dog.jpg', upload_to='mypet_images', verbose_name='반려동물 이미지'),
        ),
    ]
